logging:
  level:
    com.schoolsaas: INFO

spring:
  jpa:
    show-sql: false

server:
  error:
    include-stacktrace: never

management:
  endpoint:
    health:
      show-details: when-authorized
